name: Build

on:
  push:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S src -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        shell: bash
        env:
          TERM: xterm
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./test.exe
          else
            ./build/test/test
          fi

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p dist
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp exdupe.exe "dist/${{ github.ref_name }}-windows.exe"
          else
            cp build/exdupe "dist/${{ github.ref_name }}-linux"
            chmod +x "dist/${{ github.ref_name }}-linux"
          fi

      - name: Update Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          files: dist/*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
